spring:

  application:
    name: transportes

  profiles:
    active: dev # Perfil por defecto

  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

  url:
    front: ${FRONT_URL}
    api: ${API_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 36000000 # 10 horas en milisegundos

---

spring:

  config:
    activate:
      on-profile: prod

  datasource:
    url: ${PROD_DB_URL}
    username: admin
    password: ${DB_PROD_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

---

spring:

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:springboot
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create-drop

springdoc:

  api-docs:
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger